#!/bin/bash
#
# File: /usr/local/bin/virsh
# Author: Evert
# Function: virsh wrapper - extended functionality
#   - resync the guest system time after virsh suspend/resume
#   - restore terminal size after virsh console
#   - aliases for suspend & resume: pause|stop & cont|continue
#   - support virsh suspend|resume --all
# See also: /usr/local/bin/forget_wrapper_path

#echo ">>> $0 $*" >&2  # debug - show bash-completion calls ;-)
source forget_wrapper_path  # enable the original command (not this wrapper)

declare -A state_filter=( [suspend]="running" [resume]="paused" )
my_virsh () {
    # support virsh suspend|resume --all
    # requires
    #   - ${state_filter[$action]} hash/dictionary (for --all)
    #   - virsh_suspend & virsh_resume functions because
    #     virsh_resume includes an additional action (resync guest system time)
    local action="$1"; shift  # suspend|resume
    case "$1" in
        --all)
            shift  # --all
            local state=${state_filter[$action]}  # running|paused
            local host  # loop var
            for host in $(virsh list --state-$state --name); do
                virsh_$action $host "$@"  # suspend|resume $host
            done
            ;;
        *)
            virsh_$action "$@"
            ;;
    esac
}

virsh_suspend () {
    # required to support virsh_$action in function my_virsh
    virsh suspend "$@"
}

virsh_resume () {
    # resync the guest system time on virsh resume
    # Note: virsh domtime needs qemu-guest-agent installed & running on the guest
    #   which requires /dev/virtio-ports/org.qemu.guest_agent.0 on the guest too.
    #   For Ubuntu-16.04+ installation, you may need:
    #   virt-install --channel unix,target_type=virtio,name=org.qemu.guest_agent.0
    virsh resume "$@" &&
        virsh domtime --sync "$@" |sed -e '/^$/d'
}

### main
action="$1"; shift
case "$action" in
    suspend|pause|stop)
        # custom aliases for suspend which may be easier to remember
        # - pause because 'virsh list' shows paused when suspended
        # - stop because it's similar to kill -STOP
        my_virsh suspend "$@"
        ;;
    resume|cont|continue)
        # custom aliases for resume which may be easier to remember
        # - cont because it's similar to kill -CONT
        # - continue for those who prefer the full word ;-)
        my_virsh resume "$@"
        ;;
    console)
        virsh console "$@"
        # restore terminal size which virsh console incorrectly leaves behind
        # Note: resize requires the xterm package
        type -P resize >/dev/null &&
            resize >/dev/null  # suppress COLUMNS/LINES on stdout
        ;;
    *)
        exec virsh "$action" "$@"
        ;;
esac

# https://serverfault.com/questions/334698/how-to-keep-time-on-resumed-kvm-guest-with-libvirt
# https://serverfault.com/questions/132197/best-practice-for-system-clock-sync-on-kvm-host
# cat /sys/devices/system/clocksource/clocksource0/current_clocksource    # kvm-clock
# cat /sys/devices/system/clocksource/clocksource0/available_clocksource  # kvm-clock tsc acpi_pm
